#!/bin/bash
set -e

run ./bin/passenger-install-apache2-module --auto
run rvmsudo ./bin/passenger-install-apache2-module --auto --no-compile
run bundle exec drake "-j$COMPILE_CONCURRENCY" test:integration:apache2
