.TH "passenger-config" "1" "1.10" "Phusion" "User Commands"
.SH "NAME"
.LP 
passenger\-config \- Show configuration settings for the Apache passenger module
.SH "SYNOPSIS"
.LP 
\fBpassenger\-config\fR \fI\-\-root\fR | \fI\-\-version\fR
.SH "DESCRIPTION"
.LP 
\fBpassenger\-config\fR shows the current configuration settings for the passenger apache module. You need to select one of the following options.
.SH "OPTIONS"
.TP 
\fB\-\-root\fR
Shows the passenger root directory
.TP 
\fB\-\-version\fR
Shows the current passenger version number
.SH "SEE ALSO"
.LP 
passenger\-memory\-stats (1), passenger\-stress\-test (1), passenger-status (8)
.LP 
User guide at http://www.modrails.com/documentation.html
.SH "AUTHOR"
.LP 
Passenger was written by the team at Phusion (http://www.phusion.nl)
.LP 
This manual page was written by Neil Wilson <neil@brightbox.co.uk> for the Ubuntu project (but may be used by others). 
