.TH "passenger-config" "1" "2.0" "Phusion Passenger" "User Commands"
.SH "NAME"
.LP 
passenger\-config \- Show configuration settings for Phusion Passenger
.SH "SYNOPSIS"
.LP 
\fBpassenger\-config\fR \fI\-\-root\fR | \fI\-\-version\fR
.SH "DESCRIPTION"
.LP 
\fBpassenger\-config\fR shows the current configuration settings for Phusion Passenger. You need to select one of the following options.
.SH "OPTIONS"
.TP 
\fB\-\-root\fR
Shows the Phusion Passenger root directory
.TP 
\fB\-\-version\fR
Shows the current Phusion Passenger version number
.SH "SEE ALSO"
.LP 
passenger\-memory\-stats(1), passenger\-stress\-test(1), passenger\-status(8)
.LP 
User guide at https://www.phusionpassenger.com/documentation_and_support
.SH "AUTHOR"
.LP 
Phusion Passenger is written by Phusion (http://www.phusion.nl)
.LP 
This manual page was written by Neil Wilson <neil@brightbox.co.uk> for the Ubuntu project (but may be used by others). 
