.TH "passenger-make-enterprisey" "8" "2.0" "Phusion Passenger" "Adminstration Commands"
.SH "NAME"
.LP 
passenger\-make-enterprisey \- activate your Phusion passenger enterprise licence
.SH "SYNOPSIS"
.LP 
\fBpassenger\-make\-enterprisey
.SH "DESCRIPTION"
.LP 
\fBpassenger\-make\-enterprisey\fR changes your ordinary everyday version of Phusion Passenger into a special enterprise version just as soon as you type in your licence key.
.LP
As everybody working at enterprise level knows, enterprise software is so much better in every possible way. So make sure you pick up your licence key today.
.SH "SEE ALSO"
Phusion Passenger Enterprise Programme (http://www.modrails.com/enterprise.html)
.SH "AUTHOR"
.LP 
Phusion Passenger is written by Phusion (http://www.phusion.nl)
.LP 
"Phusion" and "Phusion Passenger" are trademarks of Hongli Lai & Ninh Bui.
.LP 
This manual page was written by Neil Wilson <neil@brightbox.co.uk> for the Ubuntu project (but may be used by others). 
.SH "CAVEATS"
Whatever you do don't look at the source code.
