#!/usr/bin/env ruby
#
# Usage: ./dev/runner <CODE>
#
# Evaluates Ruby code in an environment that has the Phusion Passenger
# libraries loaded.

require File.expand_path(File.dirname(__FILE__) + "/../src/ruby_supportlib/phusion_passenger")
PhusionPassenger.locate_directories

while true
  if ARGV[0] =~ /^-r(.*)/
    if $1.empty?
      lib = ARGV[1]
      ARGV.shift
      ARGV.shift
    else
      lib = $1
      ARGV.shift
    end
    begin
      PhusionPassenger.require_passenger_lib(lib)
    rescue LoadError
      require(lib)
    end
  else
    break
  end
end

module PhusionPassenger
  p eval(ARGV.join(" "))
end
