# This file is overwritten by 'vagrant provision'. For the source,
# see dev/vagrant/bashrc in the Phusion Passenger source
# tree.

# Display git branch in bash prompt.
export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w$(__git_ps1 " (%s)")]\$ '

# Add Phusion Passenger command line tools to PATH.
export PATH=/vagrant/bin:$PATH

# Tell Phusion Passenger's build system to use ccache.
export USE_CCACHE=1
export CCACHE_COMPRESS=1

# Tell Phusion Passenger Standalone to run in debug mode.
export PASSENGER_DEBUG=1

export PASSENGER_VAGRANT_ENVIRONMENT=1

alias ls='ls -Fh --color'
alias dir='ls -l'
alias free='free -m'
alias df='df -h'
